# Generated by Django 5.0.2 on 2024-02-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("F_name", models.CharField(max_length=50)),
                ("L_name", models.CharField(max_length=50)),
                ("Age", models.IntegerField()),
            ],
        ),
    ]
