# Generated by Django 5.0.2 on 2024-02-17 12:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Day1", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="users",
            new_name="user",
        ),
    ]
