# Generated by Django 5.0.2 on 2024-02-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Day1", "0002_rename_users_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("F_name", models.CharField(max_length=50)),
                ("L_name", models.CharField(max_length=50)),
                ("User_name", models.CharField(max_length=20)),
                ("Email", models.EmailField(max_length=20)),
                ("Password", models.CharField(max_length=20)),
                ("confirm_Password", models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name="user",
        ),
    ]
