# Generated by Django 5.0.2 on 2024-02-17 16:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Day1", "0003_users_delete_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="confirm_Password",
        ),
    ]
